id: P2400260A
initial_creation_type: input
source_metadata:
  title: Geluk Series
  language: bo
  description: 'Texts related to the Geluk (dge lugs) School of Tibetan Buddhism:'
  volume:
    d7f128e2d2e649a8b86c8b810f86c6e6:
      title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
      parent: Aspiration Prayers
created_at: '2022-03-01T03:41:49.276321'
last_modified_at: '2022-03-01T03:41:49.276323'
